import Head from "next/head";
import Card from "../components/Card";
import Ecosystem from "../components/Ecosystem";
import Features from "../components/Features";
import Governance from "../components/Governance";
import HeroSection from "../components/HeroSection";
import PlexSection from "../components/PlexSection";

import Footer from "../Layout/Footer";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Playit-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <Features />
      <Ecosystem />
      <PlexSection />
      <Governance />
    </div>
  );
}
